export const queryKeys = {
  session: ['session'] as const,
  me: ['me'] as const,
  meUsage: ['me', 'usage'] as const,
  circles: ['circles'] as const,
  circle: (circleId: string) => ['circle', circleId] as const,
  pets: (circleId: string) => ['pets', circleId] as const,
  accessiblePets: ['pets', 'accessible'] as const,
  pet: (petId: string) => ['pet', petId] as const,
  medications: (petId: string) => ['medications', petId] as const,
  tasks: (petId: string, includeArchived = false) => ['tasks', petId, includeArchived ? 'all' : 'active'] as const,
  today: (circleId: string, date: string) => ['today', circleId, date] as const,
  timeline: (petId: string, cursor?: string) => ['timeline', petId, cursor ?? null] as const,
  alerts: (circleId: string) => ['alerts', circleId] as const,
  usage: (circleId: string) => ['usage', circleId] as const,
  notificationPrefs: (circleId: string) => ['notification-prefs', circleId] as const,
  transfers: (circleId: string, direction?: string) => ['transfers', circleId, direction ?? 'incoming'] as const,
  shares: (petId: string) => ['shares', petId] as const,
};
