export const queryKeys = {
  session: ['session'] as const,
  me: ['me'] as const,
  meUsage: ['me', 'usage'] as const,
  families: ['families'] as const,
  deletedFamilies: ['families', 'deleted'] as const,
  family: (familyId: string) => ['family', familyId] as const,
  pets: (familyId: string) => ['pets', familyId] as const,
  accessiblePets: ['pets', 'accessible'] as const,
  pet: (petId: string) => ['pet', petId] as const,
  medications: (petId: string) => ['medications', petId] as const,
  carePlans: (petId: string, includeArchived = false) => ['care-plans', petId, includeArchived ? 'all' : 'active'] as const,
  assignments: (carePlanId: string) => ['care-assignments', carePlanId] as const,
  today: (familyId: string, date: string) => ['today', familyId, date] as const,
  todayPet: (petId: string, date: string) => ['today', 'pet', petId, date] as const,
  timeline: (petId: string, cursor?: string) => ['timeline', petId, cursor ?? null] as const,
  alerts: (familyId: string) => ['alerts', familyId] as const,
  usage: (familyId: string) => ['usage', familyId] as const,
  notificationPrefs: (familyId: string) => ['notification-prefs', familyId] as const,
  transfers: (familyId: string, direction?: string) => ['transfers', familyId, direction ?? 'incoming'] as const,
  shares: (petId: string) => ['shares', petId] as const,
};
